CREATE TABLE user (id INT NOT NULL AUTO_INCREMENT, user_name VARCHAR(100) NOT NULL, password VARCHAR(50) NOT NULL, PRIMARY KEY(id));

CREATE TABLE serie (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(500) NOT NULL, PRIMARY KEY(id));

CREATE TABLE user_serie (id INT NOT NULL AUTO_INCREMENT, id_user INT NOT NULL, id_serie INT NOT NULL, episode VARCHAR(100), watch_date DATETIME, FOREIGN KEY (id_user) REFERENCES user(id), FOREIGN KEY (id_serie) REFERENCES serie(id), PRIMARY KEY(id));